/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package myapplet;

import java.io.BufferedReader;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.IOException;
import java.io.InputStreamReader;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.StringTokenizer;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author aashish
 */

public class NewJFrame3 extends javax.swing.JFrame {

    /**
     * Creates new form NewJFrame3
     */
    static String PSM,CTG,SEM,ASS,GP,ATT,LW,U,Y,ESM;
    public NewJFrame3() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox();
        jLabel5 = new javax.swing.JLabel();
        jComboBox2 = new javax.swing.JComboBox();
        jLabel6 = new javax.swing.JLabel();
        jComboBox3 = new javax.swing.JComboBox();
        jLabel7 = new javax.swing.JLabel();
        jComboBox4 = new javax.swing.JComboBox();
        jButton4 = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        jComboBox7 = new javax.swing.JComboBox();
        jLabel9 = new javax.swing.JLabel();
        jComboBox6 = new javax.swing.JComboBox();
        jLabel8 = new javax.swing.JLabel();
        jComboBox5 = new javax.swing.JComboBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Cambria", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 0, 51));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("ESTIMATE STUDENT PERFORMANCE");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(4, 4, 670, 50);

        jButton1.setText("HOME");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(50, 90, 90, 23);

        jButton2.setText("MANAGER");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(170, 90, 90, 23);

        jButton3.setText("LOGOUT");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3);
        jButton3.setBounds(290, 90, 90, 23);

        jLabel2.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel2.setText("NAME:\n");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(10, 160, 60, 20);

        jTextField1.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField1);
        jTextField1.setBounds(80, 160, 170, 30);

        jLabel3.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel3.setText("ROLL NO:");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(10, 200, 70, 19);

        jTextField2.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        getContentPane().add(jTextField2);
        jTextField2.setBounds(80, 200, 170, 30);

        jLabel4.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel4.setText("PREVIOUS SEMESTER MARKS:");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(10, 240, 220, 14);

        jComboBox1.setFont(new java.awt.Font("Dialog", 1, 10)); // NOI18N
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "FIRST", "SECOND", "THIRD", "FAIL" }));
        getContentPane().add(jComboBox1);
        jComboBox1.setBounds(230, 240, 70, 20);

        jLabel5.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel5.setText("CLASS TEST GRADE:");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(10, 280, 150, 19);

        jComboBox2.setFont(new java.awt.Font("Dialog", 1, 10)); // NOI18N
        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "POOR", "AVERAGE", "GOOD" }));
        getContentPane().add(jComboBox2);
        jComboBox2.setBounds(160, 280, 75, 20);

        jLabel6.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel6.setText("SEMINAR PERFORMANCE:");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(10, 320, 190, 19);

        jComboBox3.setFont(new java.awt.Font("Dialog", 1, 10)); // NOI18N
        jComboBox3.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "POOR", "AVERAGE", "GOOD" }));
        getContentPane().add(jComboBox3);
        jComboBox3.setBounds(200, 320, 75, 20);

        jLabel7.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel7.setText("ASSIGNMENT:");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(10, 360, 110, 19);

        jComboBox4.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "YES", "NO" }));
        getContentPane().add(jComboBox4);
        jComboBox4.setBounds(120, 360, 60, 20);

        jButton4.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jButton4.setText("SUBMIT");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4);
        jButton4.setBounds(270, 410, 100, 25);

        jLabel10.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel10.setText("LAB WORK:");
        getContentPane().add(jLabel10);
        jLabel10.setBounds(320, 360, 90, 19);

        jComboBox7.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "YES", "NO" }));
        getContentPane().add(jComboBox7);
        jComboBox7.setBounds(410, 360, 60, 20);

        jLabel9.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel9.setText("ATTENDENCE:\n");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(320, 320, 100, 19);

        jComboBox6.setFont(new java.awt.Font("Dialog", 1, 10)); // NOI18N
        jComboBox6.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "POOR", "AVERAGE", "GOOD" }));
        getContentPane().add(jComboBox6);
        jComboBox6.setBounds(420, 320, 75, 20);

        jLabel8.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel8.setText("GENERAL PROFICIENCY:");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(320, 280, 180, 14);

        jComboBox5.setFont(new java.awt.Font("Dialog", 1, 10)); // NOI18N
        jComboBox5.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "YES", "NO" }));
        getContentPane().add(jComboBox5);
        jComboBox5.setBounds(500, 280, 60, 20);

        java.awt.Dimension screenSize = java.awt.Toolkit.getDefaultToolkit().getScreenSize();
        setBounds((screenSize.width-680)/2, (screenSize.height-526)/2, 680, 526);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
NewJFrame mv=new NewJFrame();
        mv.setVisible(true);
        setVisible(false);        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
NewJFrame1 mv=new NewJFrame1();
        mv.setVisible(true);
        setVisible(false);        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
NewJFrame1 mv=new NewJFrame1();
        mv.setVisible(true);
        setVisible(false);        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
U = jTextField1.getText();
Y=jTextField2.getText();
            if ((jTextField1.getText().trim().equals(""))||(jTextField2.getText().trim().equals("")))
            {
                     JOptionPane.showMessageDialog(this, "Please Provide the Name or Roll No. ");
            }
            else{       
PSM =jComboBox1.getSelectedItem().toString();
CTG=jComboBox2.getSelectedItem().toString();
SEM=jComboBox3.getSelectedItem().toString();
ASS=jComboBox4.getSelectedItem().toString();
GP=jComboBox5.getSelectedItem().toString();
ATT=jComboBox6.getSelectedItem().toString();
LW=jComboBox7.getSelectedItem().toString();
            try {
                ESM=test();
                NewJFrame4 mv=new NewJFrame4();
                mv.U=U;
                mv.Y=Y;
                mv.ESM=ESM;
                NewJFrame4.jLabel3.setText(U);
                NewJFrame4.jLabel5.setText(Y);
                NewJFrame4.jLabel7.setText(ESM);
/*String Driver = "com.mysql.jdbc.Driver"; 
      String URL = "jdbc:mysql://localhost:3306/estimate"; 
      Class.forName(Driver); 
      System.out.println("this is database");
      Connection Conn = DriverManager.getConnection(URL, "root", "root");
      Statement S = Conn.createStatement();
       S.executeUpdate("INSERT INTO  old" +
            "VALUES ('"+U+"','"+PSM+"','"+CTG+"','"+SEM+"','"+ASS+"','"+GP+"','"+ATT+"','"+LW+"','"+ESM+"')");
  */                              
        mv.setVisible(true);
        setVisible(false);
            }/* catch (SQLException ex) {
                Logger.getLogger(NewJFrame3.class.getName()).log(Level.SEVERE, null, ex);
            } catch (ClassNotFoundException ex) {
                Logger.getLogger(NewJFrame3.class.getName()).log(Level.SEVERE, null, ex);
            } */catch (FileNotFoundException ex) {
                Logger.getLogger(NewJFrame3.class.getName()).log(Level.SEVERE, null, ex);
            } catch (IOException ex) {
                Logger.getLogger(NewJFrame3.class.getName()).log(Level.SEVERE, null, ex);
            }
        
            }// TODO add your handling code here:
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static String test() throws FileNotFoundException, IOException 
{
   FileInputStream fis=new FileInputStream("vowelWithGainRation.txt");
        BufferedReader br=new BufferedReader(new InputStreamReader(fis));
        String s,temp[] = new String[4],temp5[] = new String[4],temp3,temp1,temp2 = " ";
        StringTokenizer st;
        int i=0,j=0,h=0;
        s=br.readLine();
        s=br.readLine();
                while((s=br.readLine())!=null)
        {
             
                 st= new StringTokenizer(s," [];->=");
            //System.out.println(st.countTokens());
             i=0;
             while (st.hasMoreElements()) {
			temp[i]=(String) st.nextElement();
                        i++;
		}
             
             if((temp2.equalsIgnoreCase(temp[0]))||(h==0))
             {
                 temp3=calcy(temp[2]);
                 temp1=temp[0];
                 while((s=br.readLine())!=null)
                        {
                            st= new StringTokenizer(s," [];->=");
                            //System.out.println(st.countTokens());
                            j=0;
                            while (st.hasMoreElements()) {
                                temp5[j]=(String) st.nextElement();
                                j++;
                            }
                            if(temp5[0].equalsIgnoreCase(temp1)&temp3.equalsIgnoreCase(temp5[3])){
                                //&&(temp3==temp5[3])
                   //             System.out.println("temp"+temp5[0]);
                                break;
                            }
                        }
                 //System.out.println("temp1"+temp5[1]);
                 temp2=temp5[1];
                 h++;
             }
          }
        //System.out.println("ESM"+temp[2]);
        return temp[2];
        
     }
static String calcy(String sp)
    {
        if(sp.equalsIgnoreCase("PSM")){ 
            return PSM;}
        if(sp.equalsIgnoreCase("CTG")){ 
            return CTG;}
        if(sp.equalsIgnoreCase("SEM")){ 
            return SEM;}
        if(sp.equalsIgnoreCase("ASS")){ 
            return ASS;}
        if(sp.equalsIgnoreCase("GP")){ 
            return GP;}
        if(sp.equalsIgnoreCase("ATT")){ 
            return ATT;}
        if(sp.equalsIgnoreCase("LW")){ 
            return LW;}
        
        
        return " ";
    }


    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewJFrame3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewJFrame3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewJFrame3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewJFrame3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NewJFrame3().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JComboBox jComboBox2;
    private javax.swing.JComboBox jComboBox3;
    private javax.swing.JComboBox jComboBox4;
    private javax.swing.JComboBox jComboBox5;
    private javax.swing.JComboBox jComboBox6;
    private javax.swing.JComboBox jComboBox7;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    // End of variables declaration//GEN-END:variables
}
