/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package myapplet;

import java.io.BufferedReader;
import java.io.File;
import java.io.FileReader;
import java.io.IOException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import java.io.BufferedReader;
import jxl.*;
import jxl.read.biff.BiffException;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.IOException;
import java.io.InputStreamReader;
import java.util.StringTokenizer;
import jxl.write.Label;
import jxl.write.WritableSheet;
import jxl.write.WritableWorkbook;
import jxl.write.WriteException;


/**
 *
 * @author aashish
 */
public class NewJFrame5 extends javax.swing.JFrame {

    /**
     * Creates new form NewJFrame5
     */static String PSM,CTG,SEM,ASS,GP,ATT,LW,ESM;
     static String E[]=new String[100];
      static String E1[]=null;
       static String Merit,Gender,Percent,Type;
    public static String s,name,str1,str2;
public static String s1,name1,str11,str12,U;
public static ArrayList data=new ArrayList();
    public NewJFrame5() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Cambria", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 0, 51));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("ESTIMATE STUDENT PERFORMANCE");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(4, 4, 610, 40);

        jButton1.setText("HOME");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(50, 90, 90, 23);

        jButton2.setText("MANAGER");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(170, 90, 90, 23);

        jButton3.setText("LOGOUT");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3);
        jButton3.setBounds(290, 90, 90, 23);

        jLabel2.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel2.setText("FILE:");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(140, 190, 40, 20);

        jTextField1.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        getContentPane().add(jTextField1);
        jTextField1.setBounds(179, 190, 230, 30);

        jButton4.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jButton4.setText("UPLOAD");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4);
        jButton4.setBounds(430, 190, 90, 25);

        jButton5.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jButton5.setText("SUBMIT");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton5);
        jButton5.setBounds(280, 260, 110, 30);

        java.awt.Dimension screenSize = java.awt.Toolkit.getDefaultToolkit().getScreenSize();
        setBounds((screenSize.width-656)/2, (screenSize.height-504)/2, 656, 504);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
       JFileChooser jf=new JFileChooser();
        jf.showOpenDialog(null);
        File f=jf.getSelectedFile();
        s=f.getPath();
        name=f.getName();
        System.out.println(name);
        jTextField1.setText(s);
        
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
NewJFrame mv=new NewJFrame();
        mv.setVisible(true);
        setVisible(false);        // TODO add your handling code here:
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
NewJFrame1 mv=new NewJFrame1();
        mv.setVisible(true);
        setVisible(false);        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
NewJFrame1 mv=new NewJFrame1();
        mv.setVisible(true);
        setVisible(false);        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
            U = jTextField1.getText();
            if (jTextField1.getText().trim().equals(""))
            {
                     JOptionPane.showMessageDialog(this, "Please Provide a File to ");
            }
            if(NewJFrame8.rtf==1)
            {
            try {
                E1=excel1();
                int l=0,m=0;
                String a,b;
                for(int i=0;E1[i]!=null;i++)
                {
                    if(E1[i].equals("Fail"))
                    {
                        l++;
                    }
                    if(E1[i].equals("Pass"))
                            {
                                m++;
                            }
                }
                a=Integer.toString(l);
                b=Integer.toString(m);
                NewJFrame6 mv=new NewJFrame6();
                mv.jLabel5.setText(a);
                mv.jLabel6.setText(a);
                mv.setVisible(true);
                setVisible(false);
            } catch (WriteException ex) {
                Logger.getLogger(NewJFrame5.class.getName()).log(Level.SEVERE, null, ex);
            }
            }
            else
            {
            try {
                E1=excel();
                int l = 0,m=0,n=0,p=0;
                String a,b,c,d;
                for(int i=0;E1[i]!=null;i++)
                {
                    if(E1[i].equals("First"))
                    {
                        l++;
                    }
                    if(E1[i].equals("Second"))
                    {
                        m++;
                    }
                    if(E1[i].equals("Third"))
                    {
                        n++;
                    }
                    if(E1[i].equals("Fail"))
                    {
                        p++;
                    }
                }
                a=Integer.toString(l);
                b=Integer.toString(m);
                c=Integer.toString(n);
                d=Integer.toString(p);
                NewJFrame7 mv=new NewJFrame7();
                mv.jLabel9.setText(a);
                mv.jLabel10.setText(b);
                mv.jLabel11.setText(c);
                mv.jLabel12.setText(d);
                mv.setVisible(true);
                setVisible(false);  
            }
            // TODO add your handling code here:
            catch (WriteException ex) {
                Logger.getLogger(NewJFrame5.class.getName()).log(Level.SEVERE, null, ex);
            }
                
            }
            // TODO add your handling code here:
    }//GEN-LAST:event_jButton5ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static String[] excel() throws WriteException
    {
        String str_colArow1 ;
		try {
			int i=0,j=0,k=0,l=0,m=0,n=0,o=0,a=0,b=0;
                          
			//Create a workbook object from the file at specified location. 
			//Change the path of the file as per the location on your computer. 
			Workbook wrk1 =  Workbook.getWorkbook(new File(U));
			
			//Obtain the reference to the first sheet in the workbook
			Sheet sheet1 = wrk1.getSheet(0);
                        
			for(i=0;i<sheet1.getColumns();i++)
                        {
                            
                            Cell colArow2 = sheet1.getCell(i, 0);
                           str_colArow1 = colArow2.getContents();
                            
                            
                            if(str_colArow1.equals("PSM")) {
                                j=i;
                                System.out.println(j);
                            }
                            if(str_colArow1.equals("CTG")) {
                                k=i;
                                System.out.println(k);
                            }
                            if(str_colArow1.equals("SEM")) {
                                l=i;
                                System.out.println(l);
                            }
                            if(str_colArow1.equals("ASS")) {
                                m=i;
                                System.out.println(m);
                            }
                            if(str_colArow1.equals("GP")) {
                                n=i;
                                System.out.println(n);
                            }
                            if(str_colArow1.equals("ATT")) {
                                a=i;
                                System.out.println(a);
                            }
                            if(str_colArow1.equals("LW")) {
                                b=i;
                                System.out.println(b);
                            }
                        }    
                        for(o=1;o<sheet1.getRows();o++)
                        {
                             Cell colArow2 = sheet1.getCell(j, o);
                            PSM= colArow2.getContents();
                           colArow2 = sheet1.getCell(k, o);
                           CTG= colArow2.getContents();
                           colArow2 = sheet1.getCell(l, o);
                           SEM= colArow2.getContents();
                           colArow2 = sheet1.getCell(m, o);
                           ASS= colArow2.getContents();
                           colArow2 = sheet1.getCell(n, o);
                           GP= colArow2.getContents();
                           colArow2 = sheet1.getCell(a, o);
                           ATT= colArow2.getContents();
                           colArow2 = sheet1.getCell(k, o);
                           LW= colArow2.getContents();
                           ESM=test();
                           E[o-1]=ESM;
                           System.out.println(ESM);
                           
                        }
		            WritableWorkbook workbook = Workbook.createWorkbook(new File("Old.xls"));
                 WritableSheet sheet = workbook.createSheet("First Sheet", 0);
                 int c;
                 for(i=0;i<sheet1.getColumns();i++)
                        {
                            for(c=0;c<sheet1.getRows();c++)
                            {
                                Cell colArow2 = sheet1.getCell(i, c);
                           str_colArow1 = colArow2.getContents();
                           Label label = new Label(i, c,str_colArow1);
                           sheet.addCell(label);
                           
                            }
                        }
			Label label = new Label(i, 0,"ESM");
                           sheet.addCell(label);
                           int i1=1;
                           int j1=0;
                           while(E[j1]!=null)
                           {
                            Label label1 = new Label(i, i1,E[j1]);
                           sheet.addCell(label1);   
                           j1++;
                           i1++;
                           }
                          workbook.write();
                          workbook.close();
                        
			
		} catch (BiffException e) {
			e.printStackTrace();
		} catch (IOException e) {
			e.printStackTrace();
		}
		
                return E;
    }
        public static String test() throws FileNotFoundException, IOException 
{
   FileInputStream fis=new FileInputStream("vowelWithGainRation.txt");
        BufferedReader br=new BufferedReader(new InputStreamReader(fis));
        String s,temp[] = new String[4],temp5[] = new String[4],temp3,temp1,temp2 = " ";
        StringTokenizer st;
        int i=0,j=0,h=0;
        s=br.readLine();
        s=br.readLine();
                while((s=br.readLine())!=null)
        {
             
                 st= new StringTokenizer(s," [];->=");
            //System.out.println(st.countTokens());
             i=0;
             while (st.hasMoreElements()) {
			temp[i]=(String) st.nextElement();
                        i++;
		}
             
             if((temp2.equalsIgnoreCase(temp[0]))||(h==0))
             {
                 temp3=calcy(temp[2]);
                 temp1=temp[0];
                 while((s=br.readLine())!=null)
                        {
                            st= new StringTokenizer(s," [];->=");
                            //System.out.println(st.countTokens());
                            j=0;
                            while (st.hasMoreElements()) {
                                temp5[j]=(String) st.nextElement();
                                j++;
                            }
                            if(temp5[0].equalsIgnoreCase(temp1)&temp3.equalsIgnoreCase(temp5[3])){
                                //&&(temp3==temp5[3])
                   //             System.out.println("temp"+temp5[0]);
                                break;
                            }
                        }
                 //System.out.println("temp1"+temp5[1]);
                 temp2=temp5[1];
                 h++;
             }
          }
        //System.out.println("ESM"+temp[2]);
        return temp[2];
        
     }
static String calcy(String sp)
    {
        if(sp.equalsIgnoreCase("PSM")){ 
            return PSM;}
        if(sp.equalsIgnoreCase("CTG")){ 
            return CTG;}
        if(sp.equalsIgnoreCase("SEM")){ 
            return SEM;}
        if(sp.equalsIgnoreCase("ASS")){ 
            return ASS;}
        if(sp.equalsIgnoreCase("GP")){ 
            return GP;}
        if(sp.equalsIgnoreCase("ATT")){ 
            return ATT;}
        if(sp.equalsIgnoreCase("LW")){ 
            return LW;}
        
        
        return " ";
    }
  public static String[] excel1() throws WriteException
    {
  

              String str_colArow1 ;
		try {
			int i=0,j=0,k=0,l=0,m=0,n=0,o=0,a=0,b=0;
                          
			//Create a workbook object from the file at specified location. 
			//Change the path of the file as per the location on your computer. 
			Workbook wrk1 =  Workbook.getWorkbook(new File(U));
			
			//Obtain the reference to the first sheet in the workbook
			Sheet sheet1 = wrk1.getSheet(0);
                        
			for(i=0;i<sheet1.getColumns();i++)
                        {
                            
                            Cell colArow2 = sheet1.getCell(i, 0);
                           str_colArow1 = colArow2.getContents();
                            
                            
                            if(str_colArow1.equals("Merit")) {
                                j=i;
                                System.out.println(j);
                            }
                            if(str_colArow1.equals("Gender")) {
                                k=i;
                                System.out.println(k);
                            }
                            if(str_colArow1.equals("Percent")) {
                                l=i;
                                System.out.println(l);
                            }
                            if(str_colArow1.equals("Type")) {
                                m=i;
                                System.out.println(m);
                            }
                                                   }    
                        for(o=1;o<sheet1.getRows();o++)
                        {
                             Cell colArow2 = sheet1.getCell(j, o);
                            Merit= colArow2.getContents();
                           colArow2 = sheet1.getCell(k, o);
                           Gender= colArow2.getContents();
                           colArow2 = sheet1.getCell(l, o);
                           Percent= colArow2.getContents();
                           colArow2 = sheet1.getCell(m, o);
                           Type= colArow2.getContents();
                           colArow2 = sheet1.getCell(n, o);
                           ESM=test1();
                           E[o-1]=ESM;
                           System.out.println(ESM);
                           
                        }
		WritableWorkbook workbook = Workbook.createWorkbook(new File("New.xls"));
                 WritableSheet sheet = workbook.createSheet("First Sheet", 0);
                 for(i=0;i<sheet1.getColumns();i++)
                        {
                            for(int c=0;c<sheet1.getRows();c++)
                            {
                                Cell colArow2 = sheet1.getCell(i, c);
                           str_colArow1 = colArow2.getContents();
                           Label label = new Label(i, c,str_colArow1);
                           sheet.addCell(label);
                           
                            }
                        }
			 Label label = new Label(i, 0,"CLASS");
                           sheet.addCell(label);
                           int i1=1;
                           int j1=0;
                           while(E[j1]!=null)
                           {
                            Label label1 = new Label(i, i1,E[j1]);
                           sheet.addCell(label1);   
                           j1++;
                           i1++;
                           }
                          workbook.write();
                          workbook.close();	
			
		} catch (BiffException e) {
			e.printStackTrace();
		} catch (IOException e) {
			e.printStackTrace();
		}
                return E;
    }
  public static String test1() throws FileNotFoundException, IOException 
{
   FileInputStream fis=new FileInputStream("vowelWithGainRatio.txt");
        BufferedReader br=new BufferedReader(new InputStreamReader(fis));
        String s,temp[] = new String[4],temp5[] = new String[4],temp3,temp1,temp2 = " ";
        StringTokenizer st;
        int i=0,j=0,h=0;
        s=br.readLine();
        s=br.readLine();
                while((s=br.readLine())!=null)
        {
             
                 st= new StringTokenizer(s," [];->=");
            //System.out.println(st.countTokens());
             i=0;
             while (st.hasMoreElements()) {
			temp[i]=(String) st.nextElement();
                        i++;
		}
             
             if((temp2.equalsIgnoreCase(temp[0]))||(h==0))
             {
                 temp3=calcy1(temp[2]);
                 temp1=temp[0];
                 while((s=br.readLine())!=null)
                        {
                            st= new StringTokenizer(s," [];->=");
                            //System.out.println(st.countTokens());
                            j=0;
                            while (st.hasMoreElements()) {
                                temp5[j]=(String) st.nextElement();
                                j++;
                            }
                            if(temp5[0].equalsIgnoreCase(temp1)&temp3.equalsIgnoreCase(temp5[3])){
                                //&&(temp3==temp5[3])
                   //             System.out.println("temp"+temp5[0]);
                                break;
                            }
                        }
                 //System.out.println("temp1"+temp5[1]);
                 temp2=temp5[1];
                 h++;
             }
          }
        //System.out.println("ESM"+temp[2]);
        return temp[2];
        
     }
static String calcy1(String sp)
    {
        if(sp.equalsIgnoreCase("Merit")){ 
            return Merit;}
        if(sp.equalsIgnoreCase("Gender")){ 
            return Gender;}
        if(sp.equalsIgnoreCase("Percent")){ 
            return Percent;}
        if(sp.equalsIgnoreCase("Type")){ 
            return Type;} 
        return " ";
    }


    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewJFrame5.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewJFrame5.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewJFrame5.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewJFrame5.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NewJFrame5().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
