/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package myapplet;

import java.io.BufferedReader;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.IOException;
import java.io.InputStreamReader;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.StringTokenizer;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author aashish
 */
public class NewJFrame9 extends javax.swing.JFrame {

    /**
     * Creates new form NewJFrame9
     */
    static String Merit,Gender,Percent,Type,U,ESM;
    public NewJFrame9() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox();
        jLabel4 = new javax.swing.JLabel();
        jComboBox2 = new javax.swing.JComboBox();
        jLabel5 = new javax.swing.JLabel();
        jComboBox3 = new javax.swing.JComboBox();
        jLabel6 = new javax.swing.JLabel();
        jComboBox4 = new javax.swing.JComboBox();
        jButton4 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Cambria", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 0, 51));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("ESTIMATE STUDENT PERFORMANCE");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(4, 4, 670, 50);

        jButton1.setText("HOME");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(50, 90, 90, 23);

        jButton2.setText("MANAGER");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(170, 90, 90, 23);

        jButton3.setText("LOGOUT");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3);
        jButton3.setBounds(290, 90, 90, 23);

        jLabel2.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel2.setText("NAME:\n");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(230, 170, 60, 20);

        jTextField1.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        getContentPane().add(jTextField1);
        jTextField1.setBounds(300, 170, 140, 20);

        jLabel3.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel3.setText("MERIT:");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(230, 220, 50, 14);

        jComboBox1.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Good", "Bad" }));
        getContentPane().add(jComboBox1);
        jComboBox1.setBounds(300, 220, 70, 22);

        jLabel4.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel4.setText("GENDER:");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(220, 260, 70, 20);

        jComboBox2.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Male", "Female" }));
        getContentPane().add(jComboBox2);
        jComboBox2.setBounds(300, 260, 70, 22);

        jLabel5.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel5.setText("PERCENT:");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(220, 300, 80, 19);

        jComboBox3.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jComboBox3.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Distinction", "First", "Second" }));
        getContentPane().add(jComboBox3);
        jComboBox3.setBounds(300, 300, 120, 22);

        jLabel6.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel6.setText("TYPE:");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(230, 340, 50, 19);

        jComboBox4.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jComboBox4.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "AI", "OTHER" }));
        getContentPane().add(jComboBox4);
        jComboBox4.setBounds(300, 340, 100, 22);

        jButton4.setText("SUBMIT");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4);
        jButton4.setBounds(310, 390, 90, 23);

        java.awt.Dimension screenSize = java.awt.Toolkit.getDefaultToolkit().getScreenSize();
        setBounds((screenSize.width-647)/2, (screenSize.height-483)/2, 647, 483);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
NewJFrame mv=new NewJFrame();
        mv.setVisible(true);
        setVisible(false);        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
U = jTextField1.getText().trim();
if ((jTextField1.getText().trim().equals("")))
{
    JOptionPane.showMessageDialog(this, "Please Provide the Name");
}
else{
Merit=jComboBox1.getSelectedItem().toString().trim();
Gender=jComboBox2.getSelectedItem().toString().trim();
Percent=jComboBox3.getSelectedItem().toString().trim();
Type=jComboBox4.getSelectedItem().toString().trim();
try {
                ESM=test();
                NewJFrame4 mv=new NewJFrame4();
                mv.U=U;
                mv.ESM=ESM;
                NewJFrame4.jLabel3.setText(U);
                NewJFrame4.jLabel7.setText(ESM);
                  String Driver = "com.mysql.jdbc.Driver"; 
      String URL = "jdbc:mysql://localhost:3306/estimate"; 
      Class.forName(Driver); 
      System.out.println("this is database");
      Connection Conn = DriverManager.getConnection(URL, "root", "root");
      Statement S = Conn.createStatement();
       S.executeUpdate("INSERT INTO new " +
            "VALUES ('"+U+"','"+Merit+"','"+Gender+"','"+Percent+"','"+Type+"','"+ESM+"')");
                
        mv.setVisible(true);
        setVisible(false);
            } catch (SQLException ex) {
                Logger.getLogger(NewJFrame9.class.getName()).log(Level.SEVERE, null, ex);
            } catch (ClassNotFoundException ex) {
                Logger.getLogger(NewJFrame9.class.getName()).log(Level.SEVERE, null, ex);}
            catch (FileNotFoundException ex) {
                Logger.getLogger(NewJFrame3.class.getName()).log(Level.SEVERE, null, ex);
            } catch (IOException ex) {
                Logger.getLogger(NewJFrame3.class.getName()).log(Level.SEVERE, null, ex);
            }      // TODO add your handling code here:
    }//GEN-LAST:event_jButton4ActionPerformed
    
}
    
    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
NewJFrame1 mv=new NewJFrame1();
        mv.setVisible(true);
        setVisible(false);        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
NewJFrame1 mv=new NewJFrame1();
        mv.setVisible(true);
        setVisible(false);        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
     public static String test() throws FileNotFoundException, IOException 
{
       FileInputStream fis=new FileInputStream("vowelWithGainRatio.txt");
        BufferedReader br=new BufferedReader(new InputStreamReader(fis));
        String s,temp[] = new String[4],temp5[] = new String[4],temp3,temp1,temp2 = " ";
        StringTokenizer st;
        int i=0,j=0,h=0;
        s=br.readLine();
        s=br.readLine();
                while((s=br.readLine())!=null)
        {
             
                 st= new StringTokenizer(s," [];->=");
            //System.out.println(st.countTokens());
             i=0;
             while (st.hasMoreElements()) {
			temp[i]=(String) st.nextElement();
                        i++;
		}
             
             if((temp2.equalsIgnoreCase(temp[0]))||(h==0))
             {
                 System.out.println("temp2"+temp[2]);
                 temp3=calcy(temp[2]);
                 System.out.println("temp3"+temp3);
                 temp1=temp[0];
                 while((s=br.readLine())!=null)
                        {
                            st= new StringTokenizer(s," [];->=");
                            //System.out.println(st.countTokens());
                            j=0;
                            while (st.hasMoreElements()) {
                                temp5[j]=(String) st.nextElement();
                                j++;
                            }
                            if(temp5[0].equalsIgnoreCase(temp1)&temp3.equalsIgnoreCase(temp5[3])){
                                //&&(temp3==temp5[3])
                                System.out.println("temp"+temp5[0]);
                                break;
                            }
                        }
                 //System.out.println("temp1"+temp5[1]);
                 temp2=temp5[1];
                 h++;
             }
          }
        System.out.println("ESM"+temp[2]);
        return temp[2];
        
     }
static String calcy(String sp)
    {
        if(sp.equalsIgnoreCase("Merit")){ 
            return Merit;}
        if(sp.equalsIgnoreCase("Gender")){ 
            return Gender;}
        if(sp.equalsIgnoreCase("Percent")){ 
            return Percent;}
        if(sp.equalsIgnoreCase("Type")){ 
            return Type;} 
        return " ";
    }

 public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewJFrame9.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewJFrame9.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewJFrame9.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewJFrame9.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NewJFrame9().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JComboBox jComboBox2;
    private javax.swing.JComboBox jComboBox3;
    private javax.swing.JComboBox jComboBox4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
